CREATE DATABASE IF NOT EXISTS panel;

USE panel;

CREATE TABLE IF NOT EXISTS admin_accounts (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    password VARCHAR(1024) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS accounts (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    password VARCHAR(1024) NOT NULL,
    os VARCHAR(32),
    expire DATETIME,
    address VARCHAR(32),
    PRIMARY KEY (id)
);